version: '3'
services:
  inventory-service:
    hostname: "inventoryService-{{.Task.ID}}"
    image: ckrieger/inventory-service:latest
    ports:
     - "5000:5000"
    restart: always 
    depends_on: 
     - rabbitmq 
    deploy: 
      mode: replicated
      replicas: 3
  shipping-service:
    hostname: "shippingService-{{.Task.ID}}"
    image: ckrieger/shipping-service:latest
    ports: 
     - "8088:8088"
    restart: always 
    depends_on: 
     - rabbitmq 
  proxy:
    hostname: "proxy"
    image: ckrieger/proxy:latest
    ports:
     - "5050:5050"
    depends_on: 
     - "rabbitmq"    
  rabbitmq:
    hostname: "my-rabbit"
    image: rabbitmq:3-management
    ports:
     - "9090:15672"
     - "5672:5672"
  monitoring-framework:
    hostname: "monitoring-framework"
    image: ckrieger/monitoring-framework:latest  
    ports: 
      - "8080:8080"
      