apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: inventory-service
  name: inventory-service
spec:
  replicas: 2
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: inventory-service
    spec:
      containers:
      - image: ckrieger/inventory-service:latest
        name: inventory-service
        ports:
        - containerPort: 5000
        resources: {}
        volumeMounts:
        - mountPath: /loggingvolume/
          name: loggingvolume
      hostname: inventoryService-{{.Task.ID}}
      restartPolicy: Always
      volumes:
      - name: loggingvolume
        persistentVolumeClaim:
          claimName: loggingvolume
status: {}
