version: '3'
services:
  inventory-service:
    build: ./inventory-service
    ports:
     - "5000:5000"
    deploy: 
      mode: replicated
      replicas: 2
  shipping-service:
    build: ./shipping-service
    ports: 
     - "8088:8088"