version: '3'
services:
  inventory-service:
    image: ckrieger/inventory-service:latest
    ports:
     - "5000:5000"
    deploy: 
      mode: replicated
      replicas: 2
  shipping-service:
    image: ckrieger/shipping-service:latest
    ports: 
     - "8088:8088"