version: '3'
services:
  inventory-service:
    hostname: "inventoryService-{{.Task.ID}}"
    image: ckrieger/inventory-service:latest
    volumes: 
     - "loggingvolume:/loggingvolume/"
    ports:
     - "5000:5000"
    restart: always 
    depends_on: 
     - rabbitmq 
    deploy: 
      mode: replicated
      replicas: 2
  shipping-service:
    hostname: "shippingService-{{.Task.ID}}"
    image: ckrieger/shipping-service:latest
    volumes: 
     - "loggingvolume:/loggingvolume/"
    ports: 
     - "8088:8088"
    restart: always 
    depends_on: 
     - rabbitmq 
  log-collector-sidecar:
    hostname: "logCollectorSidecar"
    image: ckrieger/log-collector:latest
    volumes: 
     - "loggingvolume:/loggingvolume/"
    ports:
     - "5050:5050"
    depends_on: 
     - "rabbitmq"    
  rabbitmq:
    hostname: "my-rabbit"
    image: rabbitmq:3-management
    ports:
     - "9090:15672"
     - "5672:5672"
volumes:
 loggingvolume:         

      