version: '3'
services:
  inventory-service:
    hostname: "inventoryService-{{.Task.ID}}"
    image: ckrieger/inventory-service:latest
    ports:
     - "5000:5000"
    restart: always 
    depends_on: 
     - rabbitmq 
    deploy: 
      mode: replicated
      replicas: 2
  shipping-service:
    hostname: "shippingService-{{.Task.ID}}"
    image: ckrieger/shipping-service:latest
    ports: 
     - "8088:8088"
    restart: always 
    depends_on: 
     - rabbitmq 
  rabbitmq:
    hostname: "my-rabbit"
    image: rabbitmq:3-management
    ports:
     - "8080:15672"
     - "5672:5672"
