version: '3'
services:
  inventory-service:
    hostname: "inventory-service-{{.Task.ID}}"
    image: ckrieger/inventory-service:latest
    ports:
     - "5000:5000"
    deploy: 
      mode: replicated
      replicas: 2
  shipping-service:
    hostname: "shipping-service-{{.Task.ID}}"
    image: ckrieger/shipping-service:latest
    ports: 
     - "8088:8088"